[platformio]
core_dir = .platformio
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<main.cpp>

[env:f4_bh1750]
extends = env:esp32dev
build_src_filter = +<f4_bh1750.cpp>
